services:
  postgres:
    image: postgres:15-alpine
    container_name: retail_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_SUPERUSER_PASSWORD}
      APP_BACKEND_PASSWORD: ${APP_BACKEND_PASSWORD}
      APP_AUDITOR_PASSWORD: ${APP_AUDITOR_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d:ro,z

volumes:
  postgres_data: